apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-sqlsvr
  name: pod-sqlsvr
spec:
  containers:
  - image: nginx
    name: pod-sqlsvr
    resources: {}
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-credential
          key: db-password
