apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox
    name: privileged-pod
    securityContext:
      privileged: true
  
