apiVersion: v1
kind: Pod
metadata:
  labels:
    run: cpu-mem-limits
  name: cpu-mem-limits
  namespace: limits
spec:
  containers:
  - command:
    - sleep
    - "100"
    image: busybox:latest
    name: nginx
    resources: 
      requests:
        memory: "50Mi"
        cpu: "20m"
      limits:
        cpu: "80m"
        memory: "256Mi"
  restartPolicy: Never

