apiVersion: v1 
kind: LimitRange
metadata:
  name: stricter-limits
  namespace: lr-demo
spec:
  limits: 
  - type: Container
    max:
      cpu: "100m"
      memory: "128Mi"
    min:
      cpu: "30m"
      memory: "50Mi"
         