apiVersion: v1 
kind: Pod
metadata:
  name: test-pod-2
  namespace: lr-demo
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    resources:
      limits:
        cpu: "102m"
        memory: "130Mi"